//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contact_Book.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contact_Book.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Config&gt;
        ///  &lt;Administrator&gt;
        ///    &lt;罗宇翔&gt;
        ///      &lt;Name&gt;罗宇翔&lt;/Name&gt;
        ///      &lt;City&gt;惠州市&lt;/City&gt;
        ///      &lt;Tel&gt;18675247550&lt;/Tel&gt;
        ///      &lt;QQ&gt;422651378&lt;/QQ&gt;
        ///    &lt;/罗宇翔&gt;
        ///    &lt;娄成恺&gt;
        ///      &lt;Name&gt;娄成恺&lt;/Name&gt;
        ///      &lt;City&gt;上海市&lt;/City&gt;
        ///      &lt;Tel&gt;13331889701&lt;/Tel&gt;
        ///      &lt;QQ&gt;974786141&lt;/QQ&gt;
        ///    &lt;/娄成恺&gt;
        ///    &lt;卢伟&gt;
        ///      &lt;Name&gt;卢伟&lt;/Name&gt;
        ///      &lt;City&gt;宜春市&lt;/City&gt;
        ///      &lt;Tel&gt;18846839015&lt;/Tel&gt;
        ///      &lt;QQ&gt;1679826103&lt;/QQ&gt;
        ///    &lt;/卢伟&gt;
        ///  &lt;/Administrator&gt;
        ///  &lt;Visitor&gt;
        ///    &lt;马庆涛&gt;
        ///      &lt;Name&gt;马庆涛&lt;/Na [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string HaoKongTiaoGeLiZao {
            get {
                return ResourceManager.GetString("HaoKongTiaoGeLiZao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon MainWindow_ICO {
            get {
                object obj = ResourceManager.GetObject("MainWindow_ICO", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Config&gt;
        ///  &lt;Administrator&gt;Romantic&lt;/Administrator&gt;
        ///  &lt;Visitor&gt;00000000&lt;/Visitor&gt;
        ///&lt;/Config&gt; 的本地化字符串。
        /// </summary>
        internal static string MeiDiBianPinKongTiao {
            get {
                return ResourceManager.GetString("MeiDiBianPinKongTiao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Sign_In_BackGround {
            get {
                object obj = ResourceManager.GetObject("Sign_In_BackGround", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
